### ISSUE TITLE
Sorting and paging regression

### ISSUE THREAD

**Issue by ASLLR** [ltb-project/white-pages#72] opened 2019-07-17 14:32 UTC
Hi, 
I'm always on my WP test version 0.3. I see a big change in tab repertory (or register). In WP 0.2 we have a search module who sort the result by page. We do not have in version 0.3 the arrow on top of the colum to sort also.

0.2 :  
![image](https://user-images.githubusercontent.com/37147055/61384083-2b8ecc80-a8b0-11e9-8ce3-f8c700e3d3e0.png)

0.3 : 
![image](https://user-images.githubusercontent.com/37147055/61384127-3cd7d900-a8b0-11e9-936f-e9622e95b21d.png)

I doesn't see in documentation if it's a parameter to activate.

thank for all !

**Comment by coudot** [comment] 2019-07-17 14:36
I was looking to the same issue, there is a probem with javascript code used for datatables:
```
SyntaxError: expected expression, got '&'
```

Do you have some php / smarty version change between 0.2 and 0.3? I am trying to understand what can cause this error.

**Comment by coudot** [comment] 2019-07-17 14:43
The issue is in templates/footer.tpl:
```
{$datatables_page_length_choices|replace:'-1':($msg_pager_all|string_format:'"%s"') }
```

The quotes are put into HTML entities, and they should not.

You can override this by replacing the above expression by:
```
{$datatables_page_length_choices}
```

**Comment by coudot** [comment] 2019-07-18 07:30
I am stuck on this issue, smarty is always converting quotes into HTML entites, which is not compatible with javascript code.

I think I will be forced to remove the label translation.

If everyone has an idea...

**Comment by nqb** [comment] 2019-07-18 07:39
Hello @coudot,

Maybe @proxyconcept can help us. He did the datatables integration in White Pages no ?

**Comment by coudot** [comment] 2019-07-18 14:09
For now I have removed the replace with string_format. I will release like this if we don't find a better fix bfore 0.3 release.

**Comment by ASLLR** [comment] 2019-07-18 14:42
i patch my file and the display like WP 0.2 is here. Nice.

**Comment by coudot** [comment] 2019-07-22 08:16
I found the issue, it is beaucse of #58 : all printed strings are HTML escaped

I will see how to fix this.

**Comment by coudot** [comment] 2019-07-22 09:26
Hello @ASLLR i found a fix, see https://github.com/ltb-project/white-pages/commit/a02d54f79c05a645bea0d44a1e822495d7549881

I'm closing this issue, thanks for the report and the tests!

**Closed by coudot** 2019-07-22 09:26 UTC
Labels: bug
